@host=http://localhost:8000


###### USER ROUTES ######

### create user ###
POST {{host}}/user/signup
content-type: application/json

{   
    "email":"krishna@gmail.com",
    "password": "abcdf"
}


### create user ###

POST {{host}}/user/signup
content-type: application/json

{
    "password": "abc"
}
### must give form validation error###


### create user ###

POST {{host}}/user/signup
content-type: application/json

{
    "email": "abc@gmail.com"
}
### must give form validation error###

### login user ###
POST {{host}}/user/login
content-type: application/json

{   
    "email": "abc@gmail.com",
    "password": "abc"
}
### should login the user correctly ###

POST {{host}}/user/login
content-type: application/json

{   
    "email": "abcdefg@gmail.com",
    "password": "abc"
}
### should return message that email or password is wrong ###

POST {{host}}/user/login
content-type: application/json

{   
    "email": "abc@gmail.com",
    "password": "abcdef"
}
### should return message that email or password is wrong ###

POST {{host}}/user/login
content-type: application/json

{   
    "email": "a@gmail.com",
    "password": "abc"
}
### should return message that user doesnot exist ###



###### NEWS ROUTES ######

### get news data ###
GET {{host}}/news
content-type: application/json



### get filtered news data ###
GET {{host}}/news/getByFilter
content-type: application/json

{   
    "filter": "MARS"
}


### get latest news ###
GET {{host}}/news/latestNews
content-type: application/json




###### WEATHER ROUTES ######

### get weather data ###
GET {{host}}/weather
content-type: application/json