import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import 'tailwindcss/tailwind.css'
import React, { useEffect, useState, useContext } from 'react';

import { useCreateTeamMutation } from '../app/services/APISlice'


interface IProps {}
const inter = Inter({ subsets: ['latin'] })

const Home: React.FC<IProps> = () => {
  return (
    <>
      <Head>
        <title>news-portal read anything, anywhere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="image" href="/assets/Thanos.jpg" />
      </Head>
      <main>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>
        <div className='text-[black]'>gfhjkl</div>

      </main>
    </>
  )
}

export default Home;
