/* eslint-disable linebreak-style */
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import 'tailwindcss/tailwind.css';
import React, { useEffect, useState, useContext } from 'react';

// eslint-disable-next-line linebreak-style
import { useGetLatestNewsQuery, useGetNewsQuery } from '../app/services/APISlice';
import { NavBar } from '../components';
import { TopComponent, LatestNews } from '../components';


// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface IProps {
  pageProps:any
  setIsFetching:any
 }
const inter = Inter({ subsets: ['latin'] });

const Home: React.FC<IProps> = (pageProps, setIsFetching) => {
  
    const { isError:hotTopicsError, isLoading:hotTopicsLoading, data:latestNewsData } = useGetLatestNewsQuery();
    const { isError:allNewsError, isLoading:allNewsLoading, data:allNewsData } = useGetNewsQuery();
    
    return (
        <>
            <Head>
                <title>news-portal read anything, anywhere</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="image" href="/assets/Thanos.jpg" />
            </Head>
            <main>
                <NavBar/>
                <div className='bg-[white] w-full flex flex-col justify-center items-center mt-[100px]'>
                    <TopComponent {...{latestNewsData}}/>
                    <LatestNews {...{allNewsData}}/>
                </div>
            </main>
        </>
    );
};

export default Home;
